# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/drlogout/iredmail-cli
    steps:
      - checkout
      - run: sudo cp .circleci/iredmail-release /etc/iredmail-release
      - run: sudo cp .circleci/doveadm /usr/local/bin/doveadm
      - run: sudo chmod a+x /usr/local/bin/doveadm
      - run: cp .circleci/my.cnf-vmailadmin $HOME/.my.cnf-vmailadmin
      - run: go get -v -t -d ./...
      - run: go test -v ./integration_test
      - run: git config --global user.name drlogout
      - run: make dist
      - run: make release
        
workflows:
  version: 2
  run_release:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
